# 2.2 Sklearn

* 데이터 불러오기
* 2.2.1. 싸이킷-런 데이터 분리
* 2.2.2. 싸이킷-런 지도 학습
* 2.2.3. 싸이킷-런 비지도 학습
* 2.2.4. 싸이킷-런 특징 추출

In [9]:
# pip install scikit-learn
import sklearn   # 머신러닝 라이브러리
sklearn.__version__

'0.20.1'

### 데이터 불러오기

In [10]:
from sklearn.datasets import load_iris  # 직관적이고 사용하기 쉬움, 내장 데이터

In [11]:
iris_dataset = load_iris()
print("iris_dataset key: {}".format(iris_dataset.keys()))

iris_dataset key: dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [12]:
print(iris_dataset['data'])
print("shape of data: {}". format(iris_dataset['data'].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [13]:
print(iris_dataset['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [14]:
print(iris_dataset['target'])
print(iris_dataset['target_names'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [15]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

## 2.2.1. 싸이킷-런 데이터 분리

In [16]:
target = iris_dataset['target']

In [17]:
from sklearn.model_selection import train_test_split  # hold-out 방법

In [18]:
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                    target,
                                                                    test_size = 0.25,
                                                                    random_state=42)  # random seed 로 매번 같은 random 순서를 가짐

# cross-val을 위한 set 나눔 (8:2)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
# X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=1)

In [19]:
print("shape of train_input: {}".format(train_input.shape))
print("shape of test_input: {}".format(test_input.shape))
print("shape of train_label: {}".format(train_label.shape))
print("shape of test_label: {}".format(test_label.shape))

shape of train_input: (112, 4)
shape of test_input: (38, 4)
shape of train_label: (112,)
shape of test_label: (38,)


## 2.2.2. 싸이킷-런 지도 학습

다목적 분류: 어떤 분류에도 괜찮은 결과를 보여줌 + 회귀에 적용하기도 좋다.

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [21]:
knn.fit(train_input, train_label)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

In [22]:
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

In [23]:
knn.predict(new_input)

array([1])

In [24]:
predict_label = knn.predict(test_input)
print(predict_label)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [25]:
print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

test accuracy 1.00


In [26]:
from sklearn.metrics import accuracy_score

print('test accuracy {:.2f}'.format(accuracy_score(test_label, predict_label)))

test accuracy 1.00


## 2.2.3. 싸이킷-런 비지도 학습

In [27]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)  # 최적의 k값 찾기

In [28]:
k_means.fit(train_input)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [29]:
k_means.labels_

array([0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 1, 2, 0,
       0, 1, 2, 0, 1, 0, 0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 1, 2, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1,
       2, 2, 0, 1, 2, 2, 0, 2, 0, 2, 2, 2, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 2])

In [30]:
print("0 cluster:", train_label[k_means.labels_ == 0])
print("1 cluster:", train_label[k_means.labels_ == 1])
print("2 cluster:", train_label[k_means.labels_ == 2])

0 cluster: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
1 cluster: [2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]
2 cluster: [2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]


In [31]:
import numpy as np
new_input  = np.array([[6.1, 2.8, 4.7, 1.2]])

In [32]:
prediction = k_means.predict(new_input)
print(prediction)

[1]


In [33]:
predict_cluster = k_means.predict(test_input)
print(predict_cluster)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 1 0 2 2 2 2 2 0 0 0 0 1 0 0 1 1
 0]


In [38]:
np_arr = np.array(predict_cluster)
np_arr[np_arr==0], np_arr[np_arr==1], np_arr[np_arr==2] = 3, 4, 5
np_arr[np_arr==3] = 0
np_arr[np_arr==4] = 1
np_arr[np_arr==5] = 2
predict_label = np_arr.tolist()
print(predict_label)

[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0]


In [39]:
# print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

test accuracy 0.95


## 2.2.4. 싸이킷-런 특징 추출
: 수치화되어 있지 않은 데이터의 경우 특징을 추출하여 수치화한다.

* CountVectorizer
* TfidfVectorizer
* HashingVectorizer

### CountVectorizer

각 텍스트에서 횟수를 기준으로 특징추출

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

In [56]:
text_data = ['나는 배가 고프다', '내일 점심 뭐먹지', '내일 공부 해야겠다', '점심 먹고 공부 해야지']

count_vectorizer = CountVectorizer()

In [57]:
count_vectorizer.fit(text_data)
# print(count_vectorizer.vocabulary_)

print(sorted(count_vectorizer.vocabulary_.items(), key=lambda x : x[1]))

[('고프다', 0), ('공부', 1), ('나는', 2), ('내일', 3), ('먹고', 4), ('뭐먹지', 5), ('배가', 6), ('점심', 7), ('해야겠다', 8), ('해야지', 9)]


In [58]:
sentence = [text_data[3]] # ['점심 먹고 공부 해야지']
print(sentence,count_vectorizer.transform(sentence).toarray())  # bag of words: one-hot 확장 -> 문장 단위
# print(count_vectorizer.transform(text_data).toarray())

# one-hot encording: 단어 단위

['점심 먹고 공부 해야지'] [[0 1 0 0 1 0 0 1 0 1]]


### TfidfVectorizer

https://programmers.co.kr/learn/courses/21/lessons/1846

TF란 특정단어가 하나의 데이터 안에서 등장하는 횟수

DF란 문서의 빈도값, 특정 단어가 여러 데이터에 자주 등장하는 횟수(문서군의 성격에 따라 결정됨) -> 역수 -> idf

TF-IDF란 어떤 단어가 해당 문서에 자주 등장하지만 다른 문서에는 많이 없는 단어일수록 높은 값을 가짐

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
text_data = ['나는 배가 고프다', '내일 점심 뭐먹지', '내일 공부 해야겠다', '점심 먹고 공부 해야지']
tfidf_vectorizer = TfidfVectorizer()

In [55]:
tfidf_vectorizer.fit(text_data)

# print(tfidf_vectorizer.vocabulary_)
print(sorted(count_vectorizer.vocabulary_.items(), key=lambda x : x[1]))

sentence = [text_data[3]] # ['점심 먹고 공부 해야지']

print('\n'+'sentence:' + sentence[0],tfidf_vectorizer.transform(sentence).toarray(), sep='\n')
print('\n'+"total:", count_vectorizer.transform(text_data).toarray(), sep='\n')
# print("total:",tfidf_vectorizer.transform(text_data).toarray(), sep='\n')

[('고프다', 0), ('공부', 1), ('나는', 2), ('내일', 3), ('먹고', 4), ('뭐먹지', 5), ('배가', 6), ('점심', 7), ('해야겠다', 8), ('해야지', 9)]

sentence:점심 먹고 공부 해야지
[[0.         0.43779123 0.         0.         0.55528266 0.
  0.         0.43779123 0.         0.55528266]]

total:
[[1 0 1 0 0 0 1 0 0 0]
 [0 0 0 1 0 1 0 1 0 0]
 [0 1 0 1 0 0 0 0 1 0]
 [0 1 0 0 1 0 0 1 0 1]]


In [4]:
# 추가) -> 토크나이징을 하면 더 좋은 결과가 나올 듯
import numpy as np

text_data = ['영희는 철수를 좋아한다.',
             '철수를 영희가 좋아한다.',
             '영희가 좋아하는 사람은 철수다.']

#tfidf_vectorizer = TfidfVectorizer()
tfidf_vectorizer = TfidfVectorizer(min_df=1) # 토큰이 나타날 최소 문서 개수, 오타나 자주 나오지 않는 특수한 전문용어 제거에 좋다. 

tfidf_vectorizer.fit(text_data)
print(tfidf_vectorizer.vocabulary_)

print("total:",tfidf_vectorizer.transform(text_data).toarray(), sep='\n')

tfidf_matrix = tfidf_vectorizer.fit_transform(text_data)

# print(tfidf_matrix.T)
document_distances = np.dot(tfidf_matrix, tfidf_matrix.T)  # 코사인 유사도 분석
print('유사도:',document_distances.toarray(), sep='\n')

{'영희는': 2, '철수를': 6, '좋아한다': 4, '영희가': 1, '좋아하는': 3, '사람은': 0, '철수다': 5}
total:
[[0.         0.         0.68091856 0.         0.51785612 0.
  0.51785612]
 [0.         0.57735027 0.         0.         0.57735027 0.
  0.57735027]
 [0.52863461 0.40204024 0.         0.52863461 0.         0.52863461
  0.        ]]
유사도:
[[1.         0.59796874 0.        ]
 [0.59796874 1.         0.23211804]
 [0.         0.23211804 1.        ]]
